/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as ChartsRouteImport } from './routes/charts'
import { Route as DeepLinkingRouteImport } from './routes/deep-linking'
import { Route as DeferredRouteImport } from './routes/deferred'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PostsRouteRouteImport } from './routes/posts/route'
import { Route as RedirectDemoRouteImport } from './routes/redirect-demo'
import { Route as AuthDashboardRouteImport } from './routes/_auth.dashboard'
import { Route as FilesSplatRouteImport } from './routes/files/$'
import { Route as PostsIndexRouteImport } from './routes/posts/index'
import { Route as PostsPostIdRouteImport } from './routes/posts/$postId'
import { Route as UsersIndexRouteImport } from './routes/users/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartsRoute = ChartsRouteImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/charts.lazy').then((d) => d.Route))
const DeepLinkingRoute = DeepLinkingRouteImport.update({
  id: '/deep-linking',
  path: '/deep-linking',
  getParentRoute: () => rootRouteImport,
} as any)
const DeferredRoute = DeferredRouteImport.update({
  id: '/deferred',
  path: '/deferred',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRouteRoute = PostsRouteRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const RedirectDemoRoute = RedirectDemoRouteImport.update({
  id: '/redirect-demo',
  path: '/redirect-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const FilesSplatRoute = FilesSplatRouteImport.update({
  id: '/files/$',
  path: '/files/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PostsRouteRoute,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => PostsRouteRoute,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/posts': typeof PostsRouteRouteWithChildren
  '/charts': typeof ChartsRoute
  '/deep-linking': typeof DeepLinkingRoute
  '/deferred': typeof DeferredRoute
  '/editor': typeof EditorRoute
  '/login': typeof LoginRoute
  '/redirect-demo': typeof RedirectDemoRoute
  '/dashboard': typeof AuthDashboardRoute
  '/files/$': typeof FilesSplatRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/posts/': typeof PostsIndexRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/charts': typeof ChartsRoute
  '/deep-linking': typeof DeepLinkingRoute
  '/deferred': typeof DeferredRoute
  '/editor': typeof EditorRoute
  '/login': typeof LoginRoute
  '/redirect-demo': typeof RedirectDemoRoute
  '/dashboard': typeof AuthDashboardRoute
  '/files/$': typeof FilesSplatRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/posts': typeof PostsIndexRoute
  '/users': typeof UsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/posts': typeof PostsRouteRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/charts': typeof ChartsRoute
  '/deep-linking': typeof DeepLinkingRoute
  '/deferred': typeof DeferredRoute
  '/editor': typeof EditorRoute
  '/login': typeof LoginRoute
  '/redirect-demo': typeof RedirectDemoRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/files/$': typeof FilesSplatRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/posts/': typeof PostsIndexRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/posts'
    | '/charts'
    | '/deep-linking'
    | '/deferred'
    | '/editor'
    | '/login'
    | '/redirect-demo'
    | '/dashboard'
    | '/files/$'
    | '/posts/$postId'
    | '/posts/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/charts'
    | '/deep-linking'
    | '/deferred'
    | '/editor'
    | '/login'
    | '/redirect-demo'
    | '/dashboard'
    | '/files/$'
    | '/posts/$postId'
    | '/posts'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/posts'
    | '/_auth'
    | '/charts'
    | '/deep-linking'
    | '/deferred'
    | '/editor'
    | '/login'
    | '/redirect-demo'
    | '/_auth/dashboard'
    | '/files/$'
    | '/posts/$postId'
    | '/posts/'
    | '/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PostsRouteRoute: typeof PostsRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ChartsRoute: typeof ChartsRoute
  DeepLinkingRoute: typeof DeepLinkingRoute
  DeferredRoute: typeof DeferredRoute
  EditorRoute: typeof EditorRoute
  LoginRoute: typeof LoginRoute
  RedirectDemoRoute: typeof RedirectDemoRoute
  FilesSplatRoute: typeof FilesSplatRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charts': {
      id: '/charts'
      path: '/charts'
      fullPath: '/charts'
      preLoaderRoute: typeof ChartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deep-linking': {
      id: '/deep-linking'
      path: '/deep-linking'
      fullPath: '/deep-linking'
      preLoaderRoute: typeof DeepLinkingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deferred': {
      id: '/deferred'
      path: '/deferred'
      fullPath: '/deferred'
      preLoaderRoute: typeof DeferredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redirect-demo': {
      id: '/redirect-demo'
      path: '/redirect-demo'
      fullPath: '/redirect-demo'
      preLoaderRoute: typeof RedirectDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/files/$': {
      id: '/files/$'
      path: '/files/$'
      fullPath: '/files/$'
      preLoaderRoute: typeof FilesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof PostsRouteRoute
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof PostsRouteRoute
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PostsRouteRouteChildren {
  PostsPostIdRoute: typeof PostsPostIdRoute
  PostsIndexRoute: typeof PostsIndexRoute
}

const PostsRouteRouteChildren: PostsRouteRouteChildren = {
  PostsPostIdRoute: PostsPostIdRoute,
  PostsIndexRoute: PostsIndexRoute,
}

const PostsRouteRouteWithChildren = PostsRouteRoute._addFileChildren(
  PostsRouteRouteChildren,
)

interface AuthRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardRoute: AuthDashboardRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PostsRouteRoute: PostsRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ChartsRoute: ChartsRoute,
  DeepLinkingRoute: DeepLinkingRoute,
  DeferredRoute: DeferredRoute,
  EditorRoute: EditorRoute,
  LoginRoute: LoginRoute,
  RedirectDemoRoute: RedirectDemoRoute,
  FilesSplatRoute: FilesSplatRoute,
  UsersIndexRoute: UsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
